- name: Install MySQL
  apt:
    name: mysql-server
    state: present

- name: Start MySQL service
  service:
    name: mysql
    state: started

- name: Create database
  mysql_db:
    name: my_database
    state: present

- name: Create user
  mysql_user:
    name: my_user
    password: my_password
    priv: 'my_database.*:ALL'
    state: present
