# Configuration Dependabot pour TodoList Production
# Maintenance automatique des dépendances avec sécurité renforcée

version: 2
updates:
  # Surveillance des dépendances npm de l'application
  - package-ecosystem: "npm"
    directory: "/tp"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 5
    reviewers:
      - "YOUR-USERNAME"
    assignees:
      - "YOUR-USERNAME"
    labels:
      - "dependencies"
      - "npm"
      - "automated"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    # Regroupement des updates mineurs
    groups:
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "patch"
    # Ignorer certaines dépendances si nécessaire
    ignore:
      # Exemple: ignorer les updates majeures de certains packages
      - dependency-name: "express"
        update-types: ["version-update:semver-major"]
    # Auto-merge configuration (security updates prioritized)
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  # Surveillance des GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 3
    reviewers:
      - "YOUR-USERNAME"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci-cd"
    commit-message:
      prefix: "chore(actions)"
      include: "scope"
    # Regrouper les updates des actions
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Surveillance Docker (Dockerfile)
  - package-ecosystem: "docker"
    directory: "/tp/deployment/docker"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 2
    reviewers:
      - "YOUR-USERNAME"
    labels:
      - "dependencies"
      - "docker"
      - "infrastructure"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"

  # Surveillance pip (si utilisé pour Ansible)
  - package-ecosystem: "pip"
    directory: "/tp/deployment/ansible"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 2
    reviewers:
      - "YOUR-USERNAME"
    labels:
      - "dependencies" 
      - "python"
      - "ansible"
    commit-message:
      prefix: "chore(ansible)"
      include: "scope"
